In [16]:
import pandas as pd
import os

In [17]:
rm_vis_file=os.path.join("..","Resources","Rocky_Mountin_Monthly_Recreation_Visitors.csv")
rm_visitors_df=pd.read_csv(rm_vis_file)
rm_visitors_df

,Year,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,2021,"140,715",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,"126,866","110,667","97,690",0,"63,051","491,355","723,478","580,368","500,019","297,665","157,875","156,165"
2,2019,"118,152","99,873","146,414","160,259","280,351","698,224","973,992","830,039","752,320","374,003","123,376","113,050"
3,2018,"111,422","84,245","156,434","151,975","305,993","720,822","931,929","798,306","784,480","312,757","125,349","106,781"
4,2017,"95,602","98,832","145,110","158,360","263,222","741,247","885,478","782,625","681,160","332,526","140,223","112,830"
5,2016,"115,207","105,125","135,053","129,967","285,868","700,990","912,507","772,849","711,110","398,525","158,553","91,831"
6,2015,"98,928","85,123","134,304","116,959","259,711","608,796","858,426","765,579","644,350","371,558","118,398","93,784"
7,2014,"77,633","76,881","99,077","97,100","220,532","538,725","693,685","616,826","537,694","305,651","90,915","80,032"
8,2013,"78,022","68,831","89,691","90,379","239,184","602,508","712,583","621,852","253,467","66,275","86,379","81,970"
9,2012,"68,537","62,036","104,374","117,053","228,950","500,206","651,722","589,131","527,172","219,946","93,714","66,776"
10,2011,"68,641","50,540","73,760","77,183","163,587","500,733","743,741","620,534","483,780","264,617","68,076","61,749"
11,2010,"64,618","44,576","70,117","69,097","180,710","441,738","668,418","574,638","461,942","245,770","67,862","66,335"
12,2009,"70,858","58,375","75,022","58,842","207,827","426,453","626,907","568,455","443,488","171,959","67,894","46,245"
13,2008,"62,228","58,860","71,260","63,083","165,489","420,334","611,760","533,886","424,613","213,467","74,914","57,496"
14,2007,"51,340","51,929","77,306","75,190","188,187","468,770","653,885","559,939","442,327","204,583","70,953","50,974"
15,2006,"55,549","51,901","59,636","73,816","187,936","451,277","641,178","516,531","412,722","177,716","61,323","54,091"
16,2005,"60,206","61,932","60,125","60,341","178,599","417,346","658,903","556,353","406,772","199,748","79,707","58,336"
17,2004,"57,795","58,503","79,540","62,595","179,887","421,739","633,725","561,913","407,864","200,180","52,173","65,985"
18,2003,"61,472","48,224","63,999","69,226","198,771","457,861","678,086","626,473","465,941","262,699","69,681","64,823"
19,2002,"64,696","62,365","78,997","72,485","228,491","491,045","653,677","598,693","428,493","183,445","57,455","68,633"
20,2001,"62,319","66,820","73,736","82,007","198,797","499,970","749,500","616,789","463,160","184,616","81,020","60,951"
21,2000,"67,728","74,328","83,498","82,564","211,790","483,925","735,598","597,407","448,191","242,240","85,145","72,978"
22,1999,"60,871","74,798","87,163","58,644","187,697","471,035","739,167","644,694","466,394","228,197","94,367","73,296"
23,1998,"64,192","61,194","70,334","67,735","198,448","453,744","683,467","636,460","445,728","227,638","69,927","56,555"
24,1997,"60,995","55,496","82,957","54,619","182,301","477,849","672,256","635,015","408,657","211,588","65,166","58,455"
25,1996,"50,604","56,462","69,517","73,462","177,831","442,730","669,291","658,613","405,585","194,353","61,799","63,508"
26,1995,"72,264","55,526","62,216","63,517","107,774","401,034","643,304","718,453","404,990","237,056","69,520","42,515"
27,1994,"66,336","46,474","64,501","73,383","140,442","454,741","637,208","691,826","486,600","200,637","65,256","41,046"
28,1993,"53,780","39,962","52,511","65,790","120,708","424,670","623,451","654,327","423,570","230,972","48,776","41,825"
29,1992,"60,038","48,476","58,478","80,217","160,788","408,630","606,764","623,634","440,843","218,570","47,490","34,940"
30,1991,"50,910","57,547","56,241","67,986","118,351","434,810","614,118","642,734","385,524","237,608","43,136","42,816"
31,1990,"53,565","49,896","65,280","60,274","108,881","435,279","560,806","646,018","392,873","164,130","73,064","37,257"
32,1989,"60,075","52,050","60,381","52,044","92,436","370,174","590,130","600,617","358,910","183,199","54,061","28,838"
33,1988,"58,824","52,367","56,677","57,933","91,676","399,197","568,028","617,184","371,318","178,657","55,402","36,948"
34,1987,"77,184","52,922","54,316","59,363","136,049","365,757","546,231","621,584","359,746","171,484","50,425","36,803"
35,1986,"74,949","38,588","58,001","67,259","111,710","303,208","547,751","643,670","338,915","126,243","45,674","52,266"
36,1985,"68,416","47,012","55,707","58,854","117,475","327,505","501,624","585,115","304,574","87,250","52,986","42,336"
37,1984,"51,124","49,126","46,210","46,736","75,806","303,393","514,848","605,465","355,768","93,927","52,850","36,195"
38,1983,"67,598","70,480","60,310","79,542","91,340","322,393","552,473","625,132","432,745","193,914","76,969","26,110"
39,1982,"65,547","59,558","64,554","74,092","106,375","366,311","573,923","613,132","360,870","177,760","51,377","50,617"
40,1981,"52,645","47,256","63,637","78,529","130,744","439,671","674,786","677,202","430,738","202,193","51,650","62,191"
41,1980,"42,902","59,403","58,790","64,299","93,210","410,449","573,465","609,383","389,771","219,495","51,344","69,426"
42,1979,"53,585","85,931","75,070","66,873","79,577","368,257","553,294","600,221","376,202","198,374","50,283","60,863"

In [18]:
mv_vis_file=os.path.join("..","Resources","Mesa_Verde_Monthly_Recreation_Visitors.csv")
mv_visitors_df=pd.read_csv(mv_vis_file)
mv_visitors_df

,Year,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,2020,"6,872","7,422","10,193",0,"3,029","48,110","49,824","56,923","44,557","37,794","13,803","8,950"
1,2019,95,"3,414","14,992","32,428","60,665","108,231","113,166","87,133","70,865","47,270","10,201","7,743"
2,2018,"8,309","7,400","21,048","34,517","64,623","99,530","106,001","84,092","70,929","45,178","13,382","8,411"
3,2017,"5,601","5,737","21,016","34,568","64,239","111,130","119,918","96,470","77,036","51,351","14,824","11,898"
4,2016,"6,222","7,899","20,491","28,457","58,043","104,543","119,412","93,570","72,553","50,419","14,510","7,408"
5,2015,"5,813","5,759","14,616","31,721","55,079","97,331","114,814","90,545","67,970","43,659","11,230","8,788"
6,2014,"6,199","6,531","17,391","29,800","53,608","91,640","103,586","89,201","50,725","36,961","10,522","5,399"
7,2013,"5,758","5,573","13,963","23,005","52,250","87,746","99,900","82,980","60,415","9,002","11,471","8,174"
8,2012,"6,288","5,771","14,411","25,245","51,503","85,908","98,574","81,558","60,439","40,982","10,620","7,561"
9,2011,"5,788","5,323","14,311","24,325","59,077","113,928","120,840","103,413","70,453","37,264","9,906","7,701"
10,2010,"4,212","4,549","12,112","26,390","54,833","111,802","116,017","101,458","69,169","40,243","10,758","8,169"
11,2009,"4,978","5,435","14,645","23,865","52,419","108,944","118,091","98,797","67,224","37,587","11,591","6,801"
12,2008,"4,096","6,240","18,573","24,653","56,220","107,110","113,173","98,280","69,946","38,298","9,712","5,145"
13,2007,"4,101","6,533","18,123","24,362","54,087","101,158","108,353","103,321","67,942","31,684","12,157","9,281"
14,2006,"5,200","6,847","13,867","25,631","55,129","105,832","118,270","100,106","72,272","32,829","11,991","9,274"
15,2005,"5,188","5,035","16,579","22,892","52,117","95,570","105,330","88,348","57,200","31,087","11,057","7,930"
16,2004,"3,718","3,859","14,438","21,649","42,616","80,600","96,448","81,771","52,791","33,497","8,771","6,653"
17,2003,"5,240","4,533","11,270","22,083","41,268","83,797","86,887","82,861","47,380","36,768","10,814","5,689"
18,2002,"5,411","6,075","13,074","21,309","54,699","80,180","75,745","51,962","48,431","34,395","9,067","6,037"
19,2001,"5,953","5,890","14,448","25,140","50,627","91,085","112,374","97,236","56,142","37,384","11,533","5,597"
20,2000,"5,476","5,424","13,508","24,834","54,544","94,990","75,939","62,877","61,826","36,896","9,227","6,746"
21,1999,"5,659","6,060","18,890","23,073","60,979","112,029","140,050","127,159","79,689","43,272","11,626","7,250"
22,1998,"4,647","4,246","13,083","24,699","59,334","106,280","134,922","120,282","77,771","44,159","8,074","7,059"
23,1997,"4,176","4,411","16,079","24,749","58,024","113,185","145,272","131,793","74,904","40,824","8,937","5,366"
24,1996,"4,222","5,373","16,284","28,480","64,551","111,471","149,493","104,854","72,755","43,592","10,444","5,841"
25,1995,"4,683","6,375","16,118","26,730","61,234","106,569","168,285","135,332","80,150","45,786","9,817","2,715"
26,1994,"6,036","3,857","18,712","25,506","64,496","116,635","156,848","144,239","82,263","50,581","9,468","6,390"
27,1993,"3,768","4,666","13,283","28,573","64,748","113,462","150,932","142,614","79,541","48,728","10,015","5,724"
28,1992,"5,090","6,545","14,674","31,207","67,353","136,273","172,012","158,503","86,893","48,508","10,097","4,925"
29,1991,"3,885","6,001","12,317","22,225","61,574","96,769","173,774","158,191","80,823","45,855","11,434","5,227"
30,1990,"3,926","4,232","12,856","25,531","56,647","111,215","142,952","136,687","69,788","33,157","9,583","4,801"
31,1989,"2,990","3,401","14,593","21,683","57,557","111,661","128,270","134,791","70,471","37,899","10,457","6,272"
32,1988,"3,753","5,577","14,533","26,583","79,298","128,602","172,929","164,245","108,421","52,549","10,617","5,076"
33,1987,"4,386","4,441","9,726","23,938","75,867","125,223","165,166","156,573","101,517","45,013","12,266","4,450"
34,1986,"7,497","4,799","16,430","20,449","66,006","111,035","154,908","147,714","81,426","33,974","7,980","6,670"
35,1985,"5,346","4,628","10,218","20,971","65,931","117,501","155,297","139,039","82,706","36,328","11,246","7,060"
36,1984,"2,528","3,078","8,663","14,269","47,117","92,120","117,588","120,858","72,038","26,087","7,636","4,883"
37,1983,"3,584","3,200","7,680","14,620","65,574","108,195","141,833","130,249","79,709","38,707","8,364","2,400"
38,1982,"1,200","1,872","5,552","13,090","57,751","117,150","146,716","141,005","73,581","32,393","9,010","3,648"
39,1981,"3,402","1,808","3,200","12,104","65,226","108,301","141,882","130,318","77,007","35,166","7,378","2,816"
40,1980,"1,488","1,152","3,411","10,747","49,573","98,423","131,207","133,071","68,377","30,755","7,245","3,808"
41,1979,"1,664","1,840","6,368","12,209","1,711","87,622","123,625","123,412","70,815","34,938","6,375","3,136"

In [19]:
bc_vis_file=os.path.join("..","Resources","Black_Canyon_Monthly_Recreation_Visitors.csv")
bc_visitors_df=pd.read_csv(bc_vis_file)
bc_visitors_df

,Year,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,2021,"8,759","7,287",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,"8,107","9,112","5,849","19,803","25,976","27,583","61,521","58,097","48,257","47,739","23,249","6,327"
2,2019,"4,921","6,369","12,180","25,077","75,198","75,289","51,368","80,046","48,420","25,828","22,684","5,438"
3,2018,"7,600","5,231","7,687","11,728","48,554","42,306","44,962","46,511","46,915","22,062","21,674","3,732"
4,2017,"6,925","3,361","7,147","11,292","29,218","40,616","44,532","40,788","45,983","54,766","19,473","3,042"
5,2016,"5,510","3,932","2,850","9,871","28,055","34,433","47,029","34,384","38,169","19,113","8,955","5,717"
6,2015,"4,600","4,136","5,968","8,896","23,176","33,141","45,328","27,197","29,878","16,626","5,550","4,670"
7,2014,"3,469","4,031","4,302","6,761","21,157","28,536","42,253","25,712","24,788","13,432","4,925","3,679"
8,2013,"4,046","3,410","6,698","8,606","23,708","21,927","37,010","33,279","23,945","5,789","3,296","4,138"
9,2012,509,717,"4,388","9,150","24,991","41,757","37,371","26,047","23,919","12,742","7,126","3,853"
10,2011,"3,289","3,207","4,012","4,885","12,722","24,589","28,381","39,032","26,905","12,297","5,031","3,986"
11,2010,"2,519","3,034","3,199","4,421","21,259","24,477","35,398","27,367","24,297","21,331","3,646","5,396"
12,2009,"2,896","2,936","4,137","6,378","17,349","28,824","33,975","28,343","26,428","11,553","6,075","2,557"
13,2008,"2,070","2,196","3,064","4,434","19,572","19,712","33,123","27,066","21,143","14,443","6,925","6,437"
14,2007,"7,105","5,254","14,622","14,944","22,728","30,105","33,598","29,479","24,181","23,626","11,811","2,123"
15,2006,"2,438","2,210","5,605","6,675","17,967","24,686","27,032","23,525","24,219","19,483","4,361","2,249"
16,2005,"2,454","3,263","2,814","6,683","17,785","33,902","43,429","30,978","21,662","12,606","3,490","1,748"
17,2004,"2,629","2,812","5,450","5,871","16,492","31,476","35,467","29,364","23,925","14,142","5,180","2,773"
18,2003,"3,237","2,133","3,695","5,817","22,931","26,230","35,243","27,237","20,690","12,256","4,183","3,595"
19,2002,"3,208","2,790","5,042","6,635","9,169","46,508","32,125","30,032","20,399","11,413","3,543","2,823"
20,2001,"2,468","2,153","3,944","6,319","17,649","29,964","42,156","30,943","26,981","12,585","4,845","1,011"
21,2000,"2,842","2,847","3,932","7,223","18,998","32,617","45,885","31,358","28,612","10,916","3,833","2,443"
22,1999,"5,787","2,444","4,875","5,290","16,589","32,819","43,484","35,456","28,557","16,821","5,369","2,651"
23,1998,"2,731","2,411","3,791","5,462","19,016","30,114","41,065","37,754","31,015","13,974","3,700","2,418"
24,1997,"2,512","2,043","4,990","5,476","18,455","32,105","52,330","45,887","27,433","12,589","3,691","2,352"
25,1996,"2,033","2,188","4,082","7,843","21,959","33,278","43,159","41,779","29,041","10,628","2,526","1,609"
26,1995,"2,537","1,999","5,042","6,858","19,919","34,624","48,386","42,794","31,517","15,930","4,393","7,114"
27,1994,"3,652","2,720","5,219","8,810","23,462","35,386","38,649","40,306","31,795","17,198","3,579","3,418"
28,1993,"3,566","3,458","7,189","8,176","26,124","49,405","73,032","70,591","46,749","21,059","5,116","4,857"
29,1992,"3,150","2,528","7,860","10,235","32,185","54,582","81,223","68,874","52,619","18,313","2,857","2,783"
30,1991,"1,489","4,163","8,100","6,585","30,146","50,663","70,418","65,442","49,838","21,242","4,047","4,203"
31,1990,"2,696","5,310","5,614","6,866","14,996","50,877","65,295","57,566","41,967","17,985","3,938","2,213"
32,1989,"2,090","3,045","8,651","7,185","23,921","47,280","68,558","67,297","35,430","16,264","5,550","3,315"
33,1988,"2,018","2,980","8,764","7,095","22,879","45,769","61,080","61,159","33,656","16,087","5,182","2,404"
34,1987,"2,959","2,573","8,752","7,035","22,763","48,986","65,920","70,313","33,799","15,420","4,403","2,516"
35,1986,"2,951","2,798","7,969","6,851","25,733","44,490","69,915","71,906","32,741","15,413","3,801","4,549"
36,1985,"2,948","2,569","3,843","7,136","22,253","42,334","64,474","64,108","32,252","16,609","3,788","3,698"
37,1984,"3,215","5,625","6,553","8,250","18,750","37,306","60,173","58,658","32,742","13,155","5,160","3,461"
38,1983,"3,675","8,250","11,550","7,781","21,893","40,249","71,247","67,744","35,603","14,854","3,972","4,800"
39,1982,"2,925","3,795","6,589","6,986","19,114","29,704","46,320","55,898","35,670","11,952","4,249","4,226"
40,1981,"4,744","2,967","3,413","10,391","26,787","37,812","56,509","55,879","42,500","16,073","5,141","4,388"
41,1980,"2,190","2,809","3,866","7,241","26,190","61,780","79,170","82,583","40,455","20,126","6,596","3,113"
42,1979,"1,920","2,846","4,980","6,476","23,145","41,962","44,158","51,759","35,063","14,520","4,723","2,734"

In [20]:
gd_vis_file=os.path.join("..","Resources","Great_Dunes_Monthly_Recreation_Visitors.csv")
gd_visitors_df=pd.read_csv(gd_vis_file)
gd_visitors_df

,Year,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
0,2021,"4,824","4,748",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,"5,232","5,820","19,560","5,227",0,"78,191","102,800","97,370","66,495","53,468","17,734","9,635"
2,2019,"4,404","5,154","19,541","25,183","68,473","122,086","103,293","81,085","52,946","32,180","8,606","4,595"
3,2018,"3,551","5,579","26,387","20,899","63,953","77,494","79,486","71,774","49,941","29,007","10,430","4,404"
4,2017,"3,173","6,547","24,744","23,064","67,737","96,529","97,242","73,579","47,673","29,763","10,510","6,374"
5,2016,"1,503","3,485","10,009","13,851","50,657","77,174","79,425","59,329","47,478","30,776","10,574","4,047"
6,2015,"1,354","1,003","8,221","10,587","40,804","60,712","56,935","54,096","36,735","23,159","3,861","2,046"
7,2014,"1,404","1,095","9,348","10,868","30,445","49,808","55,238","52,500","32,678","22,024","4,202","2,164"
8,2013,"1,399","1,059","10,845","10,486","34,661","47,565","51,852","40,309","30,624","6,776","4,953","2,312"
9,2012,"1,596","1,856","11,076","9,905","37,522","49,878","51,518","42,154","27,384","14,126","5,408","2,251"
10,2011,"1,428","2,316","9,919","9,453","43,793","58,163","62,020","44,320","26,900","14,625","4,718","2,403"
11,2010,"1,328","2,110","9,530","9,083","44,932","56,799","60,734","46,552","28,728","16,344","4,759","2,385"
12,2009,"1,130","2,474","9,912","9,068","43,265","63,117","63,938","48,506","27,018","14,490","4,822","2,215"
13,2008,"1,091","1,770","9,751","9,195","38,496","57,256","61,275","47,518","26,812","13,767","5,090","1,882"
14,2007,"1,062","1,270","11,043","10,436","39,298","58,386","63,461","46,389","30,778","16,452","4,824","1,722"
15,2006,"2,489","3,245","9,257","11,783","35,425","48,548","58,939","44,519","26,372","11,552","4,624","1,907"
16,2005,"2,456","2,952","10,057","9,876","40,181","57,239","66,396","42,963","25,525","14,690","4,507","2,747"
17,2004,"2,600","2,145","14,022","8,859","40,633","49,091","56,662","43,843","27,468","15,255","4,177","2,449"
18,2003,"2,890","2,426","9,028","9,175","36,170","51,008","51,521","44,718","21,472","15,367","5,164","2,436"
19,2002,"2,543","3,453","12,754","10,882","37,122","40,553","43,769","39,205","22,976","13,991","4,614","2,914"
20,2001,"1,694","2,608","10,975","10,822","36,322","53,990","60,448","51,018","27,364","13,995","5,733","2,554"
21,2000,"3,250","4,328","11,446","7,848","35,209","49,931","59,995","44,171","24,841","13,416","4,094","2,260"
22,1999,"2,281","4,152","13,082","7,573","30,383","51,934","65,925","55,854","29,989","15,921","6,695","2,956"
23,1998,"1,996","2,639","9,109","8,037","40,672","50,089","60,237","55,417","30,025","14,045","4,873","2,629"
24,1997,"2,776","3,726","23,190","8,977","40,591","59,136","65,685","60,284","27,037","13,438","3,159","1,856"
25,1996,"2,379","3,939","12,844","10,589","37,583","57,846","65,486","67,957","29,010","13,638","4,635","3,377"
26,1995,"2,728","4,919","11,615","9,570","47,068","60,781","78,406","58,269","26,669","15,949","5,345","2,344"
27,1994,"2,417","2,722","12,702","10,301","53,521","70,882","63,072","54,663","23,517","11,080","4,022","3,326"
28,1993,"1,436","1,946","14,145","11,503","39,127","57,242","63,250","58,846","28,217","13,477","3,054","2,039"
29,1992,"1,979","2,523","8,637","10,923","34,730","52,752","66,861","60,292","31,139","16,759","2,654","1,405"
30,1991,"3,804","4,504","11,355","11,956","35,654","54,439","59,034","57,160","33,418","17,417","3,063","3,266"
31,1990,"2,945","3,887","8,646","12,210","33,811","48,432","55,510","54,896","27,561","13,862","7,407","2,969"
32,1989,"3,134","2,562","11,997","9,773","34,772","46,414","56,665","51,626","28,726","12,213","5,977","2,462"
33,1988,"1,661","4,191","8,949","12,936","27,701","42,228","59,888","57,361","32,931","17,500","5,650","3,290"
34,1987,"3,463","3,143","7,352","8,795","18,036","44,274","53,673","47,743","17,056","14,033","5,341","3,028"
35,1986,"2,322","1,748","4,538","4,066","28,136","40,846","50,989","40,123","28,545","11,885","4,788","3,463"
36,1985,"2,449","2,452","4,957","6,622","19,887","35,610","42,247","40,033","19,068","5,478","1,969","1,941"
37,1984,"1,981","2,142","3,460","5,217","16,597","23,944","28,880","29,211","17,354","6,829","3,726","2,492"
38,1983,"2,604","2,818","5,251","6,138","15,981","25,662","32,897","27,816","16,728","9,099","3,385","1,798"
39,1982,"2,176","2,601","5,636","7,958","21,412","31,143","35,644","33,226","19,673","9,564","3,844","2,396"
40,1981,"3,540","3,137","4,796","8,417","18,309","24,109","36,137","35,796","20,262","10,255","4,703","3,044"
41,1980,"1,479","1,367","1,721","3,410","14,493","25,547","32,085","30,327","15,925","9,368","3,450","3,255"
42,1979,"1,696","2,054","3,261","7,848","15,791","30,219","33,439","45,930","12,819","7,192","1,231","1,066"